# -*- coding: utf-8 -*-
"""Project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_7ag3l0DS8pYRRk9pIuPkWPmT3YkbmCJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

np.random.seed(1)

rows = 8000

df = pd.DataFrame({
    "Order_ID": np.arange(10001, 10001 + rows),
    "Order_Date": pd.to_datetime(
        np.random.choice(pd.date_range("2022-01-01", "2024-12-31"), rows)
    ),
    "Region": np.random.choice(["North", "South", "East", "West", None], rows),
    "Product": np.random.choice(
        ["Laptop", "Mobile", "Tablet", "Printer", "Monitor"], rows
    ),
    "Sales": np.round(np.random.uniform(500, 60000, rows), 2),
    "Profit": np.round(np.random.uniform(-2000, 15000, rows), 2),
    "Quantity": np.random.randint(1, 12, rows)
})

# introduce duplicates
df = pd.concat([df, df.sample(200)])

print("Raw data shape:", df.shape)

# remove duplicates
df.drop_duplicates(inplace=True)

# handle missing regions
df["Region"].fillna("Unknown", inplace=True)

# remove negative sales (invalid)
df = df[df["Sales"] > 0]

print("Cleaned data shape:", df.shape)

df["Year"] = df["Order_Date"].dt.year
df["Month"] = df["Order_Date"].dt.month
df["Profit_Margin"] = round((df["Profit"] / df["Sales"]) * 100, 2)

total_sales = df["Sales"].sum()
total_profit = df["Profit"].sum()
avg_order_value = df["Sales"].mean()

print("\n--- KPI SUMMARY ---")
print("Total Sales:", round(total_sales, 2))
print("Total Profit:", round(total_profit, 2))
print("Average Order Value:", round(avg_order_value, 2))

monthly_sales = df.groupby("Month")["Sales"].sum()

plt.figure()
monthly_sales.plot(title="Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Sales")
plt.show()

region_sales = df.groupby("Region")["Sales"].sum().sort_values(ascending=False)

plt.figure()
region_sales.plot(kind="bar", title="Sales by Region")
plt.ylabel("Total Sales")
plt.show()

product_sales = df.groupby("Product")["Sales"].sum().sort_values(ascending=False)

plt.figure()
sns.barplot(x=product_sales.values, y=product_sales.index)
plt.title("Product-wise Sales")
plt.xlabel("Sales")
plt.show()

profit_by_product = df.groupby("Product")["Profit"].sum()

plt.figure()
profit_by_product.plot(kind="bar", title="Profit by Product")
plt.ylabel("Profit")
plt.show()

print("\n--- BUSINESS INSIGHTS ---")
print("1. Certain products generate high sales but low profit.")
print("2. Regional sales performance varies significantly.")
print("3. Sales show clear seasonal patterns.")
print("4. High profit margin products should be prioritized.")

